import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>NextJS Users App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
	  <p>Almost before we knew it</p>
    </div>
  )
}

export default Home
